import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Funning AI',
    description: 'Generated by create next app',
	icons: {
		icon: [
			{
				url: '/funning-logo-orange.png',
				href: '/funning-logo-orange.png'
			}
		]
	}
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`overflow-x-hidden h-screen w-screen p-0`}>{children}</body>
        </html>
    );
}
